### ISSUE TITLE
Posting plugin updates result in ore having an issue

### ISSUE THREAD

**Issue by eirikh1996** [windy1/Pore#1001]
**Describe the bug**

When posting a plugin update, after having deleted one and trying to repost it, ore will return an error

**To Reproduce**

**Expected behavior**

The above error should never happen and a repost should happen

**Screenshots**

https://gyazo.com/b2a1f0c2bda5f5878ac70871d78449fe

**Environment **
 - 
 - 
Windows 10, Google Chrome

**Additional context**

**Comment by Katrix** [comment]
Fixed in staging
