### ISSUE TITLE
'Mixin' applied as platform despite META-INF/sponge_plugins.json existing

### ISSUE THREAD

**Issue by AuroraLS3** [windy1/Pore#1066]
**Describe the bug**

My plugin uses one mixin and Sponge API 8. When I upload the plugin it is marked as 'Mixin' instead of 'Sponge 8.0', which prevents the newer version appearing as a promoted version

**To Reproduce**

I don't unfortunately know enough about the detection mechanism to say how to reproduce it other than use my plugin jar.

1. Download latest from https://ore.spongepowered.org/AuroraLS3/Plan/versions
2. Reupload

**Expected behavior**

Should be detected as Sponge 8.0

**Screenshots**

![image](https://user-images.githubusercontent.com/24460436/189972958-15f68c0c-1d81-429d-bb32-d5d8302a1804.png)
![image](https://user-images.githubusercontent.com/24460436/189972985-ff0b35a3-c50d-45e9-9fb8-00c7dfb8b7ef.png)

**Additional context**

- Sponge vanilla plugin configuration https://github.com/plan-player-analytics/Plan/blob/master/Plan/sponge/build.gradle#L24-L68
- Mixins json https://github.com/plan-player-analytics/Plan/blob/master/Plan/sponge/src/main/resources/plan-sponge.mixins.json

**Comment by felixoi** [comment]
Hey @AuroraLS3 I think something is wrong with your sponge_plugins.json?
It does not contain 
```
"dependencies": [
       {
          "id": "spongeapi",
          "version": "8.0.0",
          "load-order": "after",
          "optional": false
        },
       ...
]
```
as it should if it has a SpongeAPI dependency. Maybe try a clean rebuild?
The correct behaviour should add both tags to the versions.

**Comment by AuroraLS3** [comment]
Okay I think this might be an issue with the snapshot version of sponge vanilla gradle plugin instead - thanks for your input! :)
