### ISSUE TITLE
If deleted ,jar plugin file in project and re-uploading the same .jar file again, getting error of duplicate file.

### ISSUE THREAD

**Issue by EliasLucky** [windy1/Pore#1074]
**Describe the bug**
Deleted accidentally my plugin .jar file, tried to re-upload it, can't getting error:
"Found a duplicate file in project. Plugin files may only be uploaded once."

**To Reproduce**
1. Go to plugin project versions tab
2. Click on delete button on already uploaded plugin .jar file
3. Click on upload button and upload the same, accidentally previously deleted .jar file

This makes no sense, because isn't it's being deleted? I've deleted my plugin .jar file accidentally and can't upload it again, I can change the version of it, but it will make no sense.

**Expected behavior**
Uploads the same .jar file because it's already deleted, or at least finds out that I am trying to re-upload the same .jar file plugin that I've deleted some time ago, and recover it.

**Environment**
 Firefox 118.0.2-1

**Comment by Katrix** [comment]
The error is correct. Nothing to fix here. Instead ask a staff member to undelete your version
