### ISSUE TITLE
"Ore is experiencing difficulties." after clicking "Publish" for a version update when version already exists

### ISSUE THREAD

**Issue by AuroraLS3** [windy1/Pore#845]
**Describe the bug**

After uploading a version update for my plugin and writing the change log, clicking publish resulted in an error screen.

After writing this report I realized that the version already exists and that resulted in the error.

**To Reproduce**
1. Go to a plugin's ore page
2. Click on 'Versions' - Copy a number of a version that already exists
3. Click on 'New Version'
4. Upload a new version of the plugin jar, with the Plugin annotation for the old version
5. Upload the signature for the jar
6. Click on the green upload icon.
7. Write change log
8. Click on 'Publish'
9. See error

**Expected behavior**

I expected the update to release. However after realizing this is about the version already existing, I think some kind of descriptive error screen would be more appropriate.

**Screenshots**

![image](https://user-images.githubusercontent.com/24460436/59960821-199b5300-94d7-11e9-9073-d3abf9f2fbe1.png)

**Environment:**
 - Operating System & Version Windows 10
 - Browser & Version Firefox 67.0.4

**Comment by felixoi** [comment]
Fixed in https://github.com/SpongePowered/Ore/issues/789. It will be live on next deployment.
