### ISSUE TITLE
Double-spacing appearing

### ISSUE THREAD

**Issue by Dockter** [windy1/Pore#873]
**Describe the bug**
For some odd reason a specific section under my SGCraft plugin appears double-spaced.

Here:  https://ore.spongepowered.org/Dockter/SGCraft/pages/Home#configurator-options

**To Reproduce**
This is not double-spaced when in the editor so I can't seem to resolve it.

**Expected behavior**
It should appear as the other items in my lists.

**Screenshots**
![image](https://user-images.githubusercontent.com/1034770/63533748-0a368700-c4d3-11e9-85ff-95af92ecf2e5.png)

**Environment (please complete the following information):**
 - Windows 10, 2k screen, Firefox 68.0.2

**Comment by Katrix** [comment]
Can't explain why, but this seems to be standard markdown. Same thing happens on a Markdown editor I tried, and here on Github. It disappears when you either remove, or add an extra newline between the main list and the note at the end.

To illustrate

Single spacing:
- Foo
- Bar
- Baz

```
- Foo
- Bar
- Baz
```

Double spacing:
- Foo
- Bar

- Baz

```
- Foo
- Bar

- Baz
```
