### ISSUE TITLE
Home page is almost empty on Microsoft Edge.

### ISSUE THREAD

**Issue by Yeregorix** [windy1/Pore#878]
**Describe the bug**
Home page is almost empty on Microsoft Edge.

**To Reproduce**
1. Go to 'https://ore.stage.spongemc.org/' using Microsoft Edge
2. Repeat using another explorer

**Expected behavior**
A beautiful, not empty, page.

**Screenshots**
![edge vs chrome](https://user-images.githubusercontent.com/10995968/63871267-e0420080-c9bb-11e9-9e9e-9d5f49b19774.png)

**Environment**
 - Windows 10 x64
 - Microsoft Edge 42.17134.1.0, Microsoft EdgeHTML 17.17134 (ABP installed but disabled)
 - Google Chrome 76.0.3809.132 (ABP installed but disabled)

**Comment by Yeregorix** [comment]
After opening the console on Microsoft Edge, I get the following error:
![error](https://user-images.githubusercontent.com/10995968/63871754-c228d000-c9bc-11e9-9c8f-f161ed01d3e4.png)
I can translate the messages, if you need.

**Comment by felixoi** [comment]
Used a new JavaScript feature. Will fix later.

https://stackoverflow.com/questions/53628191/edge-script1028-expected-identifier-string-or-number
