### ISSUE TITLE
Always display release notes when downloading

### ISSUE THREAD

**Issue by WillBAnders** [windy1/Pore#886]
Currently, users can 'quick download' plugins using the download button provided for each version in the default versions page. Unfortunately, this allows a plugin to be downloaded without showing the release notes to users, which often contain important changes and other notices. This has resulted in multiple support issues from people who missed the required dependencies which were linked in the release notes.

When downloading a plugin from the versions page, the release notes should always be displayed. Because there's a separate warning page for unreviewed releases, I'm unsure how to accomplish this without simply removing the quick download button and requiring users to go to the release page (I'm not opposed to this, but I figure it would be more ideal to figure out another way).

**Comment by felixoi** [comment]
Can you take a look at our staging instance at https://ore.stage.spongemc.org ? We removed the quick download button in favor of promoted versions. If this fixes what you want, please close this issue.

**Comment by WillBAnders** [comment]
I don't see any change. The download button I was referring to is still there and redirects directly to the warning page to download without displaying release notes. Subsequent attempts simply open the download file window.

![Download Button](https://media.discordapp.net/attachments/612095106388066326/616635895323426817/OreDownload.png)

**Comment by felixoi** [comment]
Ah this one. Sorry, thought about the one which was right on the project page. We'll discuss this :+1:

**Comment by mbax** [comment]
How many users read the EULA when forced to? Even when forced to scroll through it? I imagine that's close to zero percent.

This is just creating a EULA-like scenario for users to ignore, and adds an extra step to downloading depending on implementation.

Users are always going to ignore changes; no matter how hard you try there will always be users with no idea why things are behaving differently after an update.

**Comment by felixoi** [comment]
Reopening this because of https://github.com/SpongePowered/Ore/issues/911
