### ISSUE TITLE
Bring back the download button

### ISSUE THREAD

**Issue by mbax** [windy1/Pore#911]
**Is your feature request related to a problem? Please describe.**
A simple download button makes for a friendly user experience.

**Describe the solution you'd like**
A download button, or choose-download button, depending on how many promoted versions there are. If there's just one, make it say [DOWNLOAD] and go right to it. If multiple versions to select from, make it say [CHOOSE YOUR DOWNLOAD] or similar, and pop up a modal window for which version to download (with details, links to changelog, whatever relevant information would be helpful).

**Describe alternatives you've considered (optional)**
A download button that always pops up a modal window.

**Comment by felixoi** [comment]
This is kinda conflicting with https://github.com/SpongePowered/Ore/issues/886. Bringing  the download button back without conflict to the other issue will result in linking to the version page and not to the actual download. That's the same as just using the link in the promoted version list. So the list would be more clear as it instantly shows all promoted versions and does not need a click to pop up a list.

**Comment by Katrix** [comment]
Vote here for "I prefer it as it is now":
![image](https://user-images.githubusercontent.com/11007080/77824387-3f0a5c80-70fa-11ea-8712-8e388b60f814.png)

**Comment by Katrix** [comment]
Vote here for "Changelog icon besides download icon":
![image](https://user-images.githubusercontent.com/11007080/77824402-59dcd100-70fa-11ea-8f5d-fd5da56a1387.png)

**Comment by Katrix** [comment]
Vote here for "Add another row, and rely less on icons":
![image](https://user-images.githubusercontent.com/11007080/77824423-76790900-70fa-11ea-9b20-4bb0f48a5052.png)

**Comment by Katrix** [comment]
Vote here for "Add a summary text on a new row":
![image](https://user-images.githubusercontent.com/11007080/77824436-8b559c80-70fa-11ea-8566-3006239ca652.png)

**Comment by Katrix** [comment]
Vote here for "I just want the download button back":
![image](https://user-images.githubusercontent.com/11007080/77824511-16cf2d80-70fb-11ea-8fd5-f425758c56fc.png)

**Comment by mbax** [comment]
Are these on the wrong issue? None of these bring back a download button to the main page, where users first see a plugin, to make the # 1 reason a user initially visits a plugin page the # 1 most obvious action to take on a cluttered plugin page.

![image](https://user-images.githubusercontent.com/181668/77825171-0197d600-70de-11ea-8282-276dc6dbfab1.png)

**Comment by Katrix** [comment]
No, that download button in that sense will never come back. Multiple promoted excludes such a button. What will happend, depending on if that design we land on is compatible with it, is that we might add something to the right of these entries.

![image](https://user-images.githubusercontent.com/11007080/77825358-a6c3a600-7100-11ea-936b-36aa9440aab5.png)

**Comment by mbax** [comment]
> Multiple promoted excludes such a button.

But I addressed this in the issue written above:

> If multiple versions to select from, make it say [CHOOSE YOUR DOWNLOAD] or similar, and pop up a modal window

Hiding the versions as just another section between project stats and page listings makes it less obvious.

**Comment by Katrix** [comment]
How is that so different than clicking on the promoted version you want, and then clicking on the download button? It's the same amount of mouseclicks, which is what I assume we want to minimize. That's will just bring up a fancier promoted versions list with more steps to bring it up. In general I want to avoid modals on Ore where we can. They can work in some instances, but in most they're just ugly.

**Comment by mbax** [comment]
Clicks are a concern, but I think this matters more. Here are some examples from the related community.

![image](https://user-images.githubusercontent.com/181668/77832577-9108ad80-710d-11ea-9909-19153c6d024b.png)
![image](https://user-images.githubusercontent.com/181668/77832583-97972500-710d-11ea-825f-d8984708e678.png)
![image](https://user-images.githubusercontent.com/181668/77832601-ada4e580-710d-11ea-812e-d7237f9c7b93.png)

From outside the community:
![image](https://user-images.githubusercontent.com/181668/77832630-db8a2a00-710d-11ea-858f-a7a06c603d6c.png)
![image](https://user-images.githubusercontent.com/181668/77832742-974b5980-710e-11ea-9fe4-97294614995e.png)


All of these sites provide an obvious download button (some of which then present you with a selection of options). When users search for something they want to add to their server, and get to that project's page, they are looking for such a download button. Ore stands out in that it does not present users with this standard expectation.

**Comment by Katrix** [comment]
Again, IF the result of this vote doesn't doesn't result in a design that excludes a simpler download button, then something like that could very well happen.

If it does happen though, it will appear in the promoted versions list, nowhere else. Maybe it will look something like this, maybe something else. I don't know, but let's first figure out which direction we should go.
![image](https://user-images.githubusercontent.com/11007080/77833373-b8bf3c00-7134-11ea-94c1-89f6fcda1216.png)
