### ISSUE TITLE
Broken links on version forum post

### ISSUE THREAD

**Issue by alexstaeding** [windy1/Pore#912]
**Describe the bug**
Links created on forum post link to `forums.spongepowered.org` instead of `ore.spongepowered.org`

**To Reproduce**
1. Create/upload a new version
2. Select "create forum post"
3. Open forum post for the new version
4. The broken links are here: `A new version has been released for <plugin>, it is available for download <here>`

**Expected behavior**

The link to `<plugin>` should take you to:
`https://ore.spongepowered.org/<devname>/<plugin>`
but it takes you to
`https://forums.spongepowered.org/<devname>/<plugin>`

The link to `<here>` should take you to
`https://ore.spongepowered.org/<devname>/<plugin>/versions/<version>`
but it takes you to
`https://forums.spongepowered.org/<devname>/<plugin>/versions/<version>`

**Screenshots**
This is the post that doesn't work
https://ore.spongepowered.org/Cableguy20/MSDataSync/discuss

**Environment **
 - MacOS
 - Chrome

**Additional context**

**Comment by felixoi** [comment]
Accepted. We use baseUrl https://github.com/SpongePowered/Ore/blob/32041ebff173b56bc65d6d0433a5f2d90c150215/ore/app/discourse/OreDiscourseApiEnabled.scala#L311. That's the url of the forums, we should use the router to generate the ore link. Commenting this because I'm on mobile.
