### ISSUE TITLE
Invalidate endpoint for session keys

### ISSUE THREAD

**Issue by LXGaming** [windy1/Pore#913]
**Is your feature request related to a problem? Please describe.**
I want to automate plugin version creation using Travis CI, the issue is it would require manually rotating a session token for Travis CI or generating a session token during the deploy process.
- Rotating a token would be a pain the ass
- Generating a session token then caching it wouldn't be secure
- Generating a token for a one time use when it could be valid for a few days to weeks isn't ideal

**Describe the solution you'd like**
The ability to invalidate a session token would make generating a token during deployment more viable and secure.

**Describe alternatives you've considered (optional)**
The ability to set an expire time when creating a session token would also be viable solution as in this case it would only need to be valid for 5 minutes to upload the jar to Ore rather than the days to weeks a token could potentially be valid for.

Obviously a maximum time would need to be enforced to prevent users making never-expiring session tokens.

This would be a better solution as it wouldn't require making an additional call to Ore's API to invalidate the token.

**Additional context**
Caching the token on Travis CI wouldn't be secure as it wouldn't be seen as a secure variable and could potentially get leaked.

**Comment by felixoi** [comment]
I agree with you. IMO we should implement both solutions you mentioned.
