### ISSUE TITLE
Cache project icons

### ISSUE THREAD

**Issue by XakepSDK** [windy1/Pore#917]
Most likely project icons won't change very often.
I think it's possible to cache them forever and give new icon via some url hack, e.g.
http://path/to/image?timestamp=0
where timestamp - last icon change timestamp

**Comment by Katrix** [comment]
We do cache project icons, so not sure what you're seeing

**Comment by XakepSDK** [comment]
Every time i open ore page, all icons are re-loaded. Assets are cached.

**Comment by Katrix** [comment]
Hm, looks like the caching headers are disappearing before they reach the user. Not quite sure why though.

**Comment by XakepSDK** [comment]
Same with https://ore.spongepowered.org/javascriptRoutes
not sure if this file should be cached
Also assets caching didn't work until Snowie did something.

**Comment by Katrix** [comment]
jsRoutes does seem to be cached at least for me. Can you double check and see if you do receive the CACHE_CONTROL header for it?

**Comment by XakepSDK** [comment]
https://puu.sh/EqHUv/cd892e255d.png

**Comment by XakepSDK** [comment]
Looks like expires overrides cache-control, your time is before 09.10.19 22:21:28?
My system time is 10.10.19

**Comment by Katrix** [comment]
All those dates have a timezone added to them. It shouldn't be a problem at all.

**Comment by XakepSDK** [comment]
Firefox 70.0b12
https://puu.sh/EqHZZ/42fa495497.png
Headers:
https://gist.github.com/XakepSDK/13bfda973127626e23ff32ccb53493ed

**Comment by Katrix** [comment]
I'm sorry, but I can't reproduce. It works fine for me, and you're receiving all the headers you should for that one.

**Comment by XakepSDK** [comment]
Try to change your time

**Comment by Katrix** [comment]
Ok, question, you say that you changed your time. Did you mean that you changed your timezone, or just the time itself? If just the time itself, then no, sorry, this is not a problem for us. You're the one in the future, and sadly we don't serve time travelers as well as others. This is AFAIK, just how HTTP works.

**Comment by XakepSDK** [comment]
Resolved. Firefox may reload some files if you press f5 or reload button
