### ISSUE TITLE
Broken download API for non approved files

### ISSUE THREAD

**Issue by Yeregorix** [windy1/Pore#933]
**Describe the bug**
The download of a non approved file using the API leads to a 500 error code.

**To Reproduce**
1. GET `https://ore.spongepowered.org/api/v1/projects/mirage/versions/1.3.12/download`.
2. Copy the url in the `post` field of the response.
3. POST the copied url.

**Expected behavior**
The file starts to download.

**Current behavior**
The server responds a 500 error code.

**Environment**
OS: Windows 10, Ubuntu 18
I tested using Java and CURL, I get the same error.

This issue affects the production instance.
I haven't tested the issue on the staging instance because I'm stuck on a 502 error code when trying to get any page since few days.

**Comment by Katrix** [comment]
Seems to be working on staging

**Comment by pbecotte** [comment]
Am getting the exact same error- you tested on staging, did you check production?

I'm pretty new to minecraft, trying to script out a repeatable server install for my son. At this point, am just going to not use ore.spongepowered - have already spent more time than I should have trying to get this working.

If its helpful I had a file with urls like `https://ore.spongepowered.org/EngineHub/WorldEdit/versions/6.1.10-SNAPSHOT/confirm`

I loop through them doing 


```
        output=$(curl -c /tmp/cookies -sSL "${url}")
        sleep 1  # I saw another ticket mentioning a race condition, so tried this
        target=$(echo $output | awk '{print $NF}' | tr -d '"')
        url="-b /tmp/cookies -d -XPOST $target"
        curl -v -JOLsS $url
```


At first, using the command returned from the initial curl command unmodified, I got 500. I tried a bunch of different stuff comparing it to the request the browser makes. If I persist cookies from the first get request and use them for the post, I get a 303- to the plugin page (not a file download - "< location: /EngineHub/WorldEdit" in this case) The only other interesting thing is if I don't add the `-d` or use `-F` to submit the csrf token like the browser does, I get a 403.

**Comment by Katrix** [comment]
Yes, this might still be an issue on prod, but it will be fixed as soon as we push a new update

**Comment by Yeregorix** [comment]
I'm now getting error 403 on prod.

**Comment by Katrix** [comment]
Check staging please. We pushed a fix there recently
