### ISSUE TITLE
Illegal request-target error when attempting to view plugin version

### ISSUE THREAD

**Issue by LXGaming** [windy1/Pore#937]
**Describe the bug**
Version names containing invalid URL characters result in the following error:
`Illegal request-target: Invalid input '[', expected segment, '/', '?' or 'EOI'...`

**To Reproduce**
- Go to https://ore.spongepowered.org/Dockter/Dynmap-GriefPrevention/versions
- Click `[GP.4.3.x]-1.1-SNAPSHOT`
- See error

**Expected behavior**
The version page should load.

**Screenshots**:
N/A

**Environment**
- Windows 10 v1909
- Chrome v78.0.3904.108
- FireFox v70.0.1

**Additional context**
Reported by Ale32bit#5164 in General on Sponge Discord (Creating an issue on GitHub so this issue doesn't get lost)

This issue can be worked around by manually encoding the version name: `versions/%5BGP.4.3.x%5D-1.1-SNAPSHOT`

**Comment by Katrix** [comment]
Should be fixed in staging
