### ISSUE TITLE
Redirect from forum to ore broken

### ISSUE THREAD

**Issue by DosMike** [windy1/Pore#943]
**Describe the bug**
I noticed the clicking at the ore-link automatically inserted into the forum topic at the very top it's not actually taking you to the ore-page. Instead it's just setting the url-path leaving you on an invalid page like forums.spongepowered.org/owner/slug

**To Reproduce**
* Go to a plugin page on the forums.
* Click the link at the top within the text
> This is a discussion topic for the Ore project, **[PLUGIN NAME](#)**. View the full project on Ore for downloads and more information.
* Get redirected to a 404 page

**Expected behavior**
The subdomain should switch to `ore.spongepowered.org`

**Screenshots**
![grafik](https://user-images.githubusercontent.com/9415671/70861261-ae818500-1f2b-11ea-9346-8189eb34a721.png)

**Environment**
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0

**Comment by felixoi** [comment]
Duplicate of https://github.com/SpongePowered/Ore/issues/912
