### ISSUE TITLE
Searches on Ore produce browser history per character entered

### ISSUE THREAD

**Issue by kencinder** [windy1/Pore#945]
Also occurs on staging

**Describe the bug**

Start typing into the search field and a "page" is generated in ones history per character entered. This can be seen in the back button of Chrome for instance, or in the history list. Also tested with Microsoft Edge to be certain it wasn't just wacky browser behavior.

**To Reproduce**

Type in search field "Grief" for instance, note that back button in browser removes one character per use of button.

**Expected behavior**

Search field should produce no such behaviour, only the actual previous page should be present in history.

**Environment **
Windows 10
Google Chrome 79.0.3945.88
Microsoft Edge 44.18362.449.0

**Comment by felixoi** [comment]
Reopening this because there is still an edge case I have to look into.

**Comment by DosMike** [comment]
The history has still a few problems when jumping back and forward. My guess is that values are not correctly pulled from the state, but I haven't looked at the code.

(Windows 10, FireFox 72.0.2, Google Chrome 79.0.3945.130, Edge)

Steps to reproduce:
* going to http://ore-stage.spongemc.org/ : search is empty
* search abc : history gets pushed
* search ore : history gets pushed
* go back : search changes to abc, but history is not popped but replaced with the previous state?
* go back : now history popped (<- correct history state)
* go back : history has popped again. search bar should be empty, but still contains abc
* go forward twice : search is still abc and the most recent state (with the ore search) is now equal to the second (abc search)

Also jumping to the empty (first) search (using the history dropdown) does not seem to doing anything
