### ISSUE TITLE
QoL: Make download file button on Reviews page bypass confirmation

### ISSUE THREAD

**Issue by ItsDoot** [windy1/Pore#967]
**Is your feature request related to a problem? Please describe.**
Downloading a plugin file during review means the confirmation prompt will always appear.

**Describe the solution you'd like**
When on the review page, it would be preferred if the download file button completely bypassed the confirmation prompt.

**Comment by Katrix** [comment]
We might reconsider this in the future, but as it is right now we don't want to add any bypasses for the download button.
