### ISSUE TITLE
URL '#' suffix makes projects break

### ISSUE THREAD

**Issue by pie-flavor** [windy1/Pore#970]
**Describe the bug**

No projects appear if you append `#` to a user page.

**To Reproduce**
Go to <https://ore.spongepowered.org/pie_flavor>. Observe my wealth of illustrious projects. Go to <https://ore.spongepowered.org/pie_flavor#>. Observe that they're all gone.

**Expected behavior**

I expect the projects to be on the screen. Especially given that editing buttons will suffix a # to the URL, which means that editing your tagline, canceling the edit, and reloading will cause the behavior too.

**Environment **
 -  Windows 10
 -  Chrome 81

**Comment by felixoi** [comment]
Can you confirm and close the issue if this is not happening anymore?

**Comment by pie-flavor** [comment]
The issue has been resolved.
