### ISSUE TITLE
Sometimes search does not works on exact match

### ISSUE THREAD

**Issue by XakepSDK** [windy1/Pore#991]
**Describe the bug**
Sometimes search does not works on exact match

**To Reproduce**
1. https://ore.spongepowered.org
2. Search for `LuckPerms`
3. No matches found
If you search for `Nucleus`, it will find Nucleus
If you search for `LuckPerm`, it will find LuckPerms

**Expected behavior**
LuckPerms found

**Screenshots**
![grafik](https://user-images.githubusercontent.com/4938483/80857933-5bdc0780-8c45-11ea-94b2-fc2be89b2c86.png)

**Environment **
Firefox 75

**Comment by Katrix** [comment]
Fixed in staging
