### ISSUE TITLE
Frozen statistics

### ISSUE THREAD

**Issue by alexstaeding** [windy1/Pore#993]
**Describe the bug**
View and download statistics are frozen. This has been the case for about two weeks now. I took three separate screenshots to show this.

## 26.4.2020

![image](https://user-images.githubusercontent.com/24614463/81151146-fce9fb80-8f80-11ea-8dc1-2624dc29dfa3.png)

## 27.4.2020

![image](https://user-images.githubusercontent.com/24614463/81151305-27d44f80-8f81-11ea-9ad7-26ac1f6dbf15.png)

## 6.5.2020

![image](https://user-images.githubusercontent.com/24614463/81152149-f6a84f00-8f81-11ea-8f1c-fee3eaf07965.png)

While the ordering and stars have changed, the views and downloads have not changed.

**Environment **
 - Windows 10
 - Chrome

**Comment by Katrix** [comment]
Fixed in staging

**Comment by ShunL12324** [comment]
This issue happened again, the download number absolutely encourages developers to develop plugins for sponge, so pls fix it ... How could the developer has the motivation to maintain the plugin if they see no one download their plugin.

**Comment by felixoi** [comment]
@Eric-liucn You are correct. We just fixed it :)
